List<String> vitems = [
  // Kitchen Items
  'Table',
  'Bed',
  'Sofa',
  'Spoon',
  'Fork',
  'Plate',
  'Cup',
  'Mug',
  'Knife',
  'Bottle',
  'Pillow',
  'Blanket',
  'Laptop',
  'Phone',
  'Lamp',
  'Desk',
  'Refrigerator',
  'Oven',
  'Microwave',
  'Toaster',
  'Towel',
  'Book',
  'Notebook',
  'Pen',
  'Bag',
  'Wallet',
  'Shoe',
  'Shirt',
  'Pants',
  'Jacket',
  'Shoes',
  'Mirror',
  'Basket',
  'Clock',
  'T-shirt',
  'Chair',
  'Pan',
  'Pot',
  'Mat',
  'Curtain',
  'Cushion',
  'Shelf',
  'Glasses',
  'Watch',
  'Scissors',
  'Toothbrush',
  'Toothpaste',
  'Shampoo',
  'Conditioner',
  'Hairdryer',
  'Comb',
  'Mirror',
  'Drawer',
  'Trashcan',
  'Bucket',
  'Fan',
  'Air conditioner',
  'Heater',
  'Wall',
  'Ceiling',
  'Door',
  'Window',
  'Curtain',
  'Rug',
  'Fan',
  'Whisk',
  'Blender',
  'Grater',
  'Tongs',
  'Strainer',
  'Colander',
  'Dishwasher',
  'Hose',
  'Shovel',
  'Glove',
  'Boot',
  'Cap',
  'Socks',
  'Sweater',
  'T-shirt',
  'Jeans',
  'Shorts',
  'Belt',
  'Scarf',
  'Hat',
  'Jacket',
  'Sweatshirt',
  'Raincoat',
  'Gloves',
  'Mittens',
  'Bag',
  'Backpack',
  'Suitcase',
  'Umbrella',
  'Luggage',
  'Trolley',
  'Notebook',
  'Calculator',
  'Camera',
  'Tripod',
  'Speaker',
  'Earphones',
  'Headphones',
  'Keyboard',
  'Mouse',
  'Monitor',
  'Router',
  'Hard drive',
  'Flash drive',
  'USB cable',
  'Charger',
  'Battery',
  'Power bank',
  'Extension cord',
  'Candle',
  'Vase',
  'Picture frame',
  'Painting',
  'Plant',
  'Flower pot',
  'Curtain rod',
  'Curtain tieback',
  'Broom',
  'Dustpan',
  'Mop',
  'Bucket',
  'Plunger',
  'Ladder',
  'Paintbrush',
  'Roller',
  'Screwdriver',
  'Hammer',
  'Wrench',
  'Drill',
  'Pliers',
  'Tape measure',
  'Level',
  'Nail',
  'Bolt',
  'Screw',
  'Washer',
  'Nut',
  'Cable',
  'Wire',
  'Extension lead',
  'Extension',
  'Lawnmower',
  'Shovel',
  'Rake',
  'Hoe',
  'Trowel',
  'Spade',
  'Wheelbarrow',
  'Cushion cover',
  'Throw pillow',
  'Mattress',
  'Bed frame',
  'Wardrobe',
  'Cabinet',
  'Chest of drawers',
  'Nightstand',
  'Armchair',
  'Ottoman',
  'Coffee table',
  'Coffee',
  'End table',
  'Side table',
  'Bookshelf',
  'Storage box',
  'Shoe rack',
  'Laundry basket',
  'Iron',
  'Ironing board',
  'Clothes hanger',
  'Drying rack',
  'Clothespins',
  'Tissue box',
  'Toilet brush',
  'Toilet paper holder',
  'Soap dish',
  'Shower curtain',
  'Shower caddy',
  'Bath mat',
  'Toothpick',
  'Cotton swabs',
  'Cotton balls',
  'Hand sanitizer',
  'Lotion',
  'Perfume',
  'Aftershave',
  'Deodorant',
  'Shaving cream',
  'Razor',
  'Nail polish',
  'Nail file',
  'Makeup bag',
  'Cosmetics',
  'Hair ties',
  'Hair clips',
  'Bobby pins',
  'Hairbrush',
  'Lip balm',
  'Lipstick',
  'Earrings',
  'Necklace',
  'Bracelet',
  'Ring',
  'Bangle',
  'Keychain',
  'Sunglasses',
  'Hat',
  'Wallet',
  'Handbag',
  'Backpack',
  'Clutch',
  'Messenger bag',
  'Duffel bag',
  'Briefcase',
  'Laptop bag',
  'Shopping bag',
  'Tote bag',
  'Lunchbox',
  'Thermos',
  'Water bottle',
  'Water',
  'Coffee thermos',
  'Teapot',
  'Tea cup',
  'Teaspoon',
  'Straw',
  'Coaster',
  'Tray',
  'Ice tray',
  'Ice bucket',
  'Pizza cutter',
  'Can opener',
  'Bottle opener',
  'Garlic press',
  'Meat thermometer',
  'Meat',
  'Juicer',
  'Coffee maker',
  'Tea infuser',
  'Grill',
  'Frying pan',
  'Baking tray',
  'Roasting pan',
  'Casserole dish',
  'Cooking pot',
  'Stew pot',
  'Pressure cooker',
  'Rice cooker',
  'Slow cooker',
  'Deep fryer',
  'Wok',
  'Fondue pot',
  'Sausage maker',
  'Pasta maker',
  'Ice cream maker',
  'Bread maker',
  'Cotton candy machine',
  'Popcorn maker',
  'Vegetable peeler',
  'Potato masher',
  'Peanut butter jar',
  'Jam jar',
  'Honey jar',
  'Sugar bowl',
  'Salt shaker',
  'Pepper grinder',
  'Spice rack',
  'Measuring cups',
  'Measuring spoons',
  'Kitchen scale',
  'Timer',
  'Oven mitts',
  'Dish rack',
  'Dish soap',
  'Laundry detergent',
  'Fabric softener',
  'Bleach',
  'Stain remover',
  'Broomstick',
  'Dust mop',
  'Vacuum cleaner',
  'Squeegee',
  'Chopping board',
  'Cutting board',
  'Vegetable slicer',
  'Food processor',
  'Blender',
  'Stand mixer',
  'Hand mixer',
  'Tupperware',
  'Lunch bag',
  'Food container',
  'Canister set',
  'Storage jar',
  'Thermometer',
  'First aid kit',
  'Bandage',
  'Gauze',
  'Antiseptic',
  'Alcohol swabs',
  'Pain reliever',
  'Cough syrup',
  'Tissues',
  'Thermometer',
  'Syringe',

  // Bed Items
  'Mattress',
  'Bed frame',
  'Pillow',
  'Blanket',
  'Bed sheet',
  'Comforter',
  'Quilt',
  'Duvet',
  'Pillowcase',
  'Bed skirt',
  'Headboard',
  'Nightstand',
  'Alarm clock',
  'Reading lamp',
  'Wardrobe',
  'Dresser',
  'Chest of drawers',
  'Linen',
  'Hanging organizer',
  'Blanket basket',
  'Underbed storage',
  'Curtains',
  'Rug',
  'Throw blanket',
  'Throws',
  'Cushions',
  'Bedside table',
  'Storage bins',
  'Bed topper',
  'Bed rail',
  'Bunk bed',
  'Canopy bed',

  // Car Items
  'Car seat',
  'Steering wheel',
  'Seat belt',
  'Dashboard',
  'Gear shift',
  'Brake pedal',
  'Accelerator pedal',
  'Handbrake',
  'Speedometer',
  'Odometer',
  'Fuel gauge',
  'Car key',
  'Key fob',
  'Car remote',
  'Car door handle',
  'Car mirror',
  'Side mirror',
  'Windshield',
  'Wipers',
  'Windshield washer',
  'Headlights',
  'Taillights',
  'Turn signals',
  'Fog lights',
  'License plate',
  'Car tires',
  'Spare tire',
  'Tire jack',
  'Tire pressure gauge',
  'Jack stand',
  'Car battery',
  'Car charger',
  'USB port',
  'Charging cable',
  'Air conditioning',
  'Heater',
  'Car radio',
  'CD player',
  'Speakers',
  'Bluetooth',
  'Car seat cover',
  'Sunshade',
  'Car mat',
  'Trunk',
  'Roof rack',
  'Carwash supplies',
  'Wax',
  'Polish',
  'Microfiber cloth',
  'Cleaning products',
  'Windshield cleaner',
  'Rims',
  'Hubcaps',
  'Tire cleaner',
  'Seat cushions',
  'First aid kit',
  'aid',
  'Car phone holder',
  'Car organizer',
  'Cup holder',
  'Car trash can',
  'Snow chains',
  'Jumper cables',
  'Emergency kit',
  'Tow rope',
  'Battery jumper pack',
  'Fuel canister',
  'Fire extinguisher',
  'Emergency flares',
  'Roadside assistance kit',
  'Car repair kit',
  'Car cover',
  'GPS navigator',
  'Car alarm',
  'Parking sensor',
  'Car wash kit',
  'Bluetooth speaker',
  'Car sunroof',
  'Tinted windows',
  'Car navigation system',
  'Air freshener',
  'Car phone mount',
  'Car upholstery cleaner',
  'Headrest',
  'Sun visor',
  'Car bumper',
  'Exhaust pipe',
  'Car antenna',
  'Car exhaust system',
  'Wheel alignment tool',
];
